# Generated by Django 6.0.5 on 2026-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('answ', models.TextField()),
                ('tgl', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
