# Generated by Django 6.0.5 on 2026-06-22 13:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lokasi_luaslahan_musimtanam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediksiPanen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luas_meter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('hasil_prediksi', models.CharField(blank=True, max_length=255, null=True)),
                ('lokasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediksi_panen', to='api.lokasi')),
                ('musim_tanam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediksi_panen', to='api.musimtanam')),
            ],
        ),
    ]
