# Generated by Django 6.0.5 on 2026-06-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prediksipanen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrediksiPanen',
        ),
    ]
