# Generated by Django 6.0.5 on 2026-06-24 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_prediksipanen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lahan', models.CharField(help_text='Contoh: Lahan Blok A, Lahan Sektor Utara', max_length=100)),
                ('luas_lahan', models.FloatField(help_text='Luas lahan dalam satuan Hektar (Ha)')),
                ('komoditas', models.CharField(default='Padi / Beras', max_length=100)),
                ('provinsi', models.CharField(default='Jawa Tengah', max_length=100)),
                ('kabupaten_kota', models.CharField(help_text='Contoh: Kabupaten Demak', max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_lahan', models.CharField(choices=[('SEHAT', 'Sehat'), ('WASPADA', 'Waspada'), ('TERSERANG', 'Terserang Hama/Penyakit')], default='SEHAT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusimTanam2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_panen', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_panen', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='musimtanam',
            old_name='tanggal_panen',
            new_name='tanggal_selesai',
        ),
        migrations.RemoveField(
            model_name='musimtanam',
            name='nama_panen',
        ),
        migrations.AddField(
            model_name='musimtanam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='musimtanam',
            name='nama_musim',
            field=models.CharField(default=1, help_text='Contoh: Mei - Agustus 2026', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musimtanam',
            name='lahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='musim_tanam_set', to='api.lahan'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='Agripreneur Level 1', max_length=50)),
                ('total_panen_musim', models.IntegerField(default=0, help_text='Total musim panen yang sudah dilalui')),
                ('ekspor_berhasil', models.IntegerField(default=0, help_text='Jumlah ekspor yang sukses')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lahan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lahan_set', to='api.profil'),
        ),
    ]
