# Generated by Django 6.0.5 on 2026-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lahan_musimtanam2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='lokasi_asal',
            field=models.CharField(default='Semarang, Jawa Tengah', max_length=100),
        ),
    ]
