# Generated by Django 6.0.5 on 2026-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profil_lokasi_asal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lahan',
            name='kabupaten_kota',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='lahan',
            name='provinsi',
        ),
        migrations.AddField(
            model_name='lahan',
            name='lokasi',
            field=models.CharField(default='Semarang, Indonesia', max_length=150),
        ),
    ]
