# Generated by Django 6.0.5 on 2026-07-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_lahan_kabupaten_kota_remove_lahan_kecamatan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediksiInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi_aktivitas', models.CharField(blank=True, max_length=150, null=True)),
                ('komoditas_aktivitas', models.CharField(blank=True, max_length=100, null=True)),
                ('modal', models.DecimalField(decimal_places=2, help_text='Input modal dalam Rupiah', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_set', to='api.lahan')),
            ],
            options={
                'verbose_name_plural': 'Aktivitas Tanam',
                'ordering': ['-created_at'],
            },
        ),
    ]
