# Generated by Django 6.0.5 on 2026-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_prediksiinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediksiinput',
            name='durasi_bulan',
            field=models.IntegerField(default=5, help_text='Durasi musim tanam dalam bulan'),
        ),
        migrations.AddField(
            model_name='prediksiinput',
            name='tanggal_mulai_tanam',
            field=models.DateField(blank=True, help_text='Kapan mulai menanam', null=True),
        ),
    ]
