# Generated by Django 6.0.5 on 2026-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_prediksiinput_durasi_bulan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediksiinput',
            name='luas_lahan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Luas lahan yang digunakan dalam satuan meter persegi (m2)', max_digits=10, null=True),
        ),
    ]
