# Generated by Django 6.0.5 on 2026-07-03 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_servis', '0002_riwayatdeteksi_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produk')),
                ('stok', models.IntegerField(default=1)),
                ('tgl', models.DateTimeField(auto_now_add=True)),
                ('penjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('status', models.CharField(default='Sukses', max_length=100)),
                ('tgl', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_servis.produk')),
            ],
        ),
    ]
