# Generated by Django 6.0.5 on 2026-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_servis', '0003_produk_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(choices=[('benih', 'Benih'), ('pupuk', 'Pupuk'), ('pestisida', 'Pestisida'), ('alat', 'Alat Pertanian'), ('media_tanam', 'Media Tanam')], default='benih', max_length=100),
        ),
    ]
